In [1]:
! pip install tabulate

You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.


In [6]:
from OurTrainingTools2D import *

random_seed = torch.randint(0, 1339, (1,)).item()
torch.manual_seed(random_seed)
data_path = os.getcwd() + '/toydata'

td = OurTrainingData([data_path+'/ChP_pt300_sm.h5'],
                     [data_path+'/ChP_pt300_gwm5e-2.h5',
                     data_path+'/ChP_pt300_gwm1e-1.h5',
                     data_path+'/ChP_pt300_gwm2e-1.h5',
                     data_path+'/ChP_pt300_gw5e-2.h5',
                     data_path+'/ChP_pt300_gw1e-1.h5',
                     data_path+'/ChP_pt300_gw2e-1.h5',],
                     process = 'W+Z', parameters =['Gphi[TeV**-2]','GW[TeV**-2]'], 
                     SMNLimits=int(3e6), BSMNLimits=int(5e5))

td.Data = td.Data[:, :7]
td.CurateAngles([3, 5])

Data, ParVal, Labels, Weights = td.Data, td.ParVal, td.Labels, td.Weights
Data, ParVal, Labels, Weights = Data.float(), ParVal.float(), Labels.float(), Weights.float()

Loading Data Files for Process: W+Z, with new physics Parameters: ['Gphi[TeV**-2]', 'GW[TeV**-2]']
Only 1D Implemented in Training !

Reading file .../madminer/madminer/examples/tutorial_particle_physics/toydata/ChP_pt300_gwm5e-2.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {0., -0.05}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_gwm5e-2.dat.gz
Charge = 1 --- Process = W+Z
#####

Reading file .../madminer/madminer/examples/tutorial_particle_physics/toydata/ChP_pt300_gwm1e-1.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {0., -0.1}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_gwm1e-1.dat.gz
Charge = 1 --- Process = W+Z
#####

Reading file .../madminer/madminer/examples/tutorial_particle_physics/toydata/ChP_pt300_gwm2e-1.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-

In [7]:
NSM = td.SMWeights.mean()*3000
NBSMList = [td.BSMWeightsList[i].mean()*3000 for i in range(len(td.BSMWeightsList))]

In [8]:
td.SMDataFiles[0].Parameters

array(['SM'], dtype=object)

In [13]:
h = h5py.File(data_path + '/gw_toydata.h5', 'w')

In [14]:
h.create_dataset('Data', data=Data)
h.create_dataset('Weights', data=Weights)
h.create_dataset('Labels', data=Labels)
h.create_dataset('NSM', data = NSM)
h.create_dataset('NBSMList', data=NBSMList)

<HDF5 dataset "NBSMList": shape (6,), type "<f8">

In [15]:
h.close()

# In Sample Test Data

# Out Sample Test Data

# New 2D format Data

In [3]:
from OurTrainingTools2D import *

=========== Random Seed: 372 ===========


In [6]:
td = OurTrainingData([os.getcwd()+'/toydata/ChP_pt300_sm.h5'],
                     [os.getcwd()+'/toydata/ChP_pt300_gw1e-2.h5',],
                     #os.getcwd()+'/ChPgphim45e-1NP.h5',],
                     process = 'W+Z', parameters =['Gphi[TeV**-2]','GW[TeV**-2]'], 
                     SMNLimits=int(5e5), BSMNLimits=int(5e5))

td.Data = td.Data[:, :7]
td.CurateAngles([3, 5])

Data, ParVal, Labels, Weights = td.Data, td.ParVal, td.Labels, td.Weights
Data, ParVal, Labels, Weights = Data.float(), ParVal.float(), Labels.float(), Weights.float()


NSM = td.SMWeights.mean()*3000
NBSMList = [td.BSMWeightsList[i].mean()*3000 for i in range(len(td.BSMWeightsList))]

h = h5py.File(os.getcwd()+'/toydata/gw_toydata_test_1e-2_out.h5', 'w')

h.create_dataset('Data', data=Data)
h.create_dataset('Weights', data=Weights)
h.create_dataset('Labels', data=Labels)
h.create_dataset('NSM', data = NSM)
h.create_dataset('NBSMList', data=NBSMList)

h.close()

Loading Data Files for Process: W+Z, with new physics Parameters: ['Gphi[TeV**-2]', 'GW[TeV**-2]']
Only 1D Implemented in Training !

Reading file .../madminer/madminer/examples/tutorial_particle_physics/toydata/ChP_pt300_gw1e-2.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {0., 0.01}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_gw1e-2.dat.gz
Charge = 1 --- Process = W+Z
#####

Reading file .../madminer/madminer/examples/tutorial_particle_physics/toydata/ChP_pt300_sm.h5
##### File Info:
SM = {0., 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_sm_1.dat.gz
Charge = 1 --- Process = W+Z
#####

Loaded SM Files:
['Gphi[TeV**-2]', 'GW[TeV**-2]']           #Data    XS[pb](avg.w)
---------------------------------------  -------  ---------------
tensor([[0., 0.]], dtype=torch.

In [8]:
td = OurTrainingData([os.getcwd()+'/toydata/ChP_pt300_sm.h5'],
                     [os.getcwd()+'/toydata/ChP_pt300_gw9e-3.h5',],
                     #os.getcwd()+'/ChPgphim45e-1NP.h5',],
                     process = 'W+Z', parameters =['Gphi[TeV**-2]','GW[TeV**-2]'], 
                     SMNLimits=int(5e5), BSMNLimits=int(5e5))

td.Data = td.Data[:, :7]
td.CurateAngles([3, 5])

Data, ParVal, Labels, Weights = td.Data, td.ParVal, td.Labels, td.Weights
Data, ParVal, Labels, Weights = Data.float(), ParVal.float(), Labels.float(), Weights.float()


NSM = td.SMWeights.mean()*3000
NBSMList = [td.BSMWeightsList[i].mean()*3000 for i in range(len(td.BSMWeightsList))]

h = h5py.File(os.getcwd()+'/toydata/gw_toydata_test_9e-3_out.h5', 'w')

h.create_dataset('Data', data=Data)
h.create_dataset('Weights', data=Weights)
h.create_dataset('Labels', data=Labels)
h.create_dataset('NSM', data = NSM)
h.create_dataset('NBSMList', data=NBSMList)

h.close()

Loading Data Files for Process: W+Z, with new physics Parameters: ['Gphi[TeV**-2]', 'GW[TeV**-2]']
Only 1D Implemented in Training !

Reading file .../madminer/madminer/examples/tutorial_particle_physics/toydata/ChP_pt300_gw9e-3.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {0., 0.009}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_gw9e-3.dat.gz
Charge = 1 --- Process = W+Z
#####

Reading file .../madminer/madminer/examples/tutorial_particle_physics/toydata/ChP_pt300_sm.h5
##### File Info:
SM = {0., 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_sm_1.dat.gz
Charge = 1 --- Process = W+Z
#####

Loaded SM Files:
['Gphi[TeV**-2]', 'GW[TeV**-2]']           #Data    XS[pb](avg.w)
---------------------------------------  -------  ---------------
tensor([[0., 0.]], dtype=torch

In [9]:
td = OurTrainingData([os.getcwd()+'/toydata/ChP_pt300_sm.h5'],
                     [os.getcwd()+'/toydata/ChP_pt300_gw8e-3.h5',],
                     #os.getcwd()+'/ChPgphim45e-1NP.h5',],
                     process = 'W+Z', parameters =['Gphi[TeV**-2]','GW[TeV**-2]'], 
                     SMNLimits=int(5e5), BSMNLimits=int(5e5))

td.Data = td.Data[:, :7]
td.CurateAngles([3, 5])

Data, ParVal, Labels, Weights = td.Data, td.ParVal, td.Labels, td.Weights
Data, ParVal, Labels, Weights = Data.float(), ParVal.float(), Labels.float(), Weights.float()


NSM = td.SMWeights.mean()*3000
NBSMList = [td.BSMWeightsList[i].mean()*3000 for i in range(len(td.BSMWeightsList))]

h = h5py.File(os.getcwd()+'/toydata/gw_toydata_test_8e-3_out.h5', 'w')

h.create_dataset('Data', data=Data)
h.create_dataset('Weights', data=Weights)
h.create_dataset('Labels', data=Labels)
h.create_dataset('NSM', data = NSM)
h.create_dataset('NBSMList', data=NBSMList)

h.close()

Loading Data Files for Process: W+Z, with new physics Parameters: ['Gphi[TeV**-2]', 'GW[TeV**-2]']
Only 1D Implemented in Training !

Reading file .../madminer/madminer/examples/tutorial_particle_physics/toydata/ChP_pt300_gw8e-3.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {0., 0.008}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_gw8e-3.dat.gz
Charge = 1 --- Process = W+Z
#####

Reading file .../madminer/madminer/examples/tutorial_particle_physics/toydata/ChP_pt300_sm.h5
##### File Info:
SM = {0., 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_sm_1.dat.gz
Charge = 1 --- Process = W+Z
#####

Loaded SM Files:
['Gphi[TeV**-2]', 'GW[TeV**-2]']           #Data    XS[pb](avg.w)
---------------------------------------  -------  ---------------
tensor([[0., 0.]], dtype=torch

In [21]:
td = OurTrainingData([os.getcwd()+'/toydata/ChP_pt300_sm.h5'],
                     [os.getcwd()+'/toydata/ChP_pt300_gw7e-3.h5',],
                     #os.getcwd()+'/ChPgphim45e-1NP.h5',],
                     process = 'W+Z', parameters =['Gphi[TeV**-2]','GW[TeV**-2]'], 
                     SMNLimits=int(5e5), BSMNLimits=int(5e5))

td.Data = td.Data[:, :7]
td.CurateAngles([3, 5])

Data, ParVal, Labels, Weights = td.Data, td.ParVal, td.Labels, td.Weights
Data, ParVal, Labels, Weights = Data.float(), ParVal.float(), Labels.float(), Weights.float()


NSM = td.SMWeights.mean()*3000
NBSMList = [td.BSMWeightsList[i].mean()*3000 for i in range(len(td.BSMWeightsList))]

h = h5py.File(os.getcwd()+'/toydata/gw_toydata_test_7e-3_out.h5', 'w')

h.create_dataset('Data', data=Data)
h.create_dataset('Weights', data=Weights)
h.create_dataset('Labels', data=Labels)
h.create_dataset('NSM', data = NSM)
h.create_dataset('NBSMList', data=NBSMList)

h.close()

Loading Data Files for Process: W+Z, with new physics Parameters: ['Gphi[TeV**-2]', 'GW[TeV**-2]']
Only 1D Implemented in Training !

Reading file .../madminer/madminer/examples/tutorial_particle_physics/toydata/ChP_pt300_gw7e-3.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {0., 0.007}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_gw7e-3.dat.gz
Charge = 1 --- Process = W+Z
#####

Reading file .../madminer/madminer/examples/tutorial_particle_physics/toydata/ChP_pt300_sm.h5
##### File Info:
SM = {0., 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_sm_1.dat.gz
Charge = 1 --- Process = W+Z
#####

Loaded SM Files:
['Gphi[TeV**-2]', 'GW[TeV**-2]']           #Data    XS[pb](avg.w)
---------------------------------------  -------  ---------------
tensor([[0., 0.]], dtype=torch