In [2]:
! pip install tabulate

You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.


In [3]:
from OurTrainingTools2D import *

random_seed = torch.randint(0, 1339, (1,)).item()
torch.manual_seed(random_seed)
data_path = os.getcwd() + '/toydata'

td = OurTrainingData([data_path+'/ChP_pt300_sm.h5'],
                     [data_path+'/ChP_pt300_gphi5e-2.h5',
                     data_path+'/ChP_pt300_gphi2e-1.h5',
                     data_path+'/ChP_pt300_gphi5e-1.h5',
                     data_path+'/ChP_pt300_gphim5e-2.h5',
                     data_path+'/ChP_pt300_gphim2e-1.h5',
                     data_path+'/ChP_pt300_gphim5e-1.h5',],
                     process = 'W+Z', parameters =['Gphi[TeV**-2]','GW[TeV**-2]'], 
                     SMNLimits=int(3e6), BSMNLimits=int(5e5))

td.Data = td.Data[:, :7]
td.CurateAngles([3, 5])

Data, ParVal, Labels, Weights = td.Data, td.ParVal, td.Labels, td.Weights
Data, ParVal, Labels, Weights = Data.float(), ParVal.float(), Labels.float(), Weights.float()

Loading Data Files for Process: W+Z, with new physics Parameters: ['Gphi[TeV**-2]', 'GW[TeV**-2]']
Only 1D Implemented in Training !

Reading file .../madminer/madminer/examples/tutorial_particle_physics/toydata/ChP_pt300_gphi5e-2.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {0.05, 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_gphi5e-2.dat.gz
Charge = 1 --- Process = W+Z
#####

Reading file .../madminer/madminer/examples/tutorial_particle_physics/toydata/ChP_pt300_gphi2e-1.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {0.2, 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_gphi2e-1.dat.gz
Charge = 1 --- Process = W+Z
#####

Reading file .../madminer/madminer/examples/tutorial_particle_physics/toydata/ChP_pt300_gphi5e-1.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV

In [4]:
NSM = td.SMWeights.mean()*3000
NBSMList = [td.BSMWeightsList[i].mean()*3000 for i in range(len(td.BSMWeightsList))]

In [5]:
td.SMDataFiles[0].Parameters

array(['SM'], dtype=object)

In [6]:
h = h5py.File(data_path + '/gphi_toydata.h5', 'w')

In [7]:
h.create_dataset('Data', data=Data)
h.create_dataset('Weights', data=Weights)
h.create_dataset('Labels', data=Labels)
h.create_dataset('NSM', data = NSM)
h.create_dataset('NBSMList', data=NBSMList)

<HDF5 dataset "NBSMList": shape (6,), type "<f8">

In [8]:
h.close()

# In Sample Test Data

In [30]:
td = OurTrainingData([data_path+'/ChP_pt300_sm.h5'],
                     [data_path+'/ChP_pt300_gphi5e-2.h5',],
                     process = 'W+Z', parameters =['Gphi[TeV**-2]','GW[TeV**-2]'], 
                     SMNLimits=int(5e5), BSMNLimits=int(2e6))

td.Data = td.Data[:, :7]
td.CurateAngles([3, 5])

Data, ParVal, Labels, Weights = td.Data, td.ParVal, td.Labels, td.Weights
Data, ParVal, Labels, Weights = Data.float(), ParVal.float(), Labels.float(), Weights.float()

NSM = td.SMWeights.mean()*3000
NBSMList = [td.BSMWeightsList[i].mean()*3000 for i in range(len(td.BSMWeightsList))]

h = h5py.File(os.getcwd()+'/toydata/gphi_toydata_test_5e-2_in.h5', 'w')

h.create_dataset('Data', data=Data)
h.create_dataset('Weights', data=Weights)
h.create_dataset('Labels', data=Labels)
h.create_dataset('NSM', data = NSM)
h.create_dataset('NBSMList', data=NBSMList)

h.close()

Loading Data Files for Process: W+Z, with new physics Parameters: ['Gphi[TeV**-2]', 'GW[TeV**-2]']
Only 1D Implemented in Training !

Reading file .../madminer/madminer/examples/tutorial_particle_physics/toydata/ChP_pt300_gphi5e-2.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {0.05, 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_gphi5e-2.dat.gz
Charge = 1 --- Process = W+Z
#####

Reading file .../madminer/madminer/examples/tutorial_particle_physics/toydata/ChP_pt300_sm.h5
##### File Info:
SM = {0., 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_sm_1.dat.gz
Charge = 1 --- Process = W+Z
#####

Loaded SM Files:
['Gphi[TeV**-2]', 'GW[TeV**-2]']           #Data    XS[pb](avg.w)
---------------------------------------  -------  ---------------
tensor([[0., 0.]], dtype=to

In [18]:
td = OurTrainingData([data_path+'/ChP_pt300_sm.h5'],
                     [data_path+'/ChP_pt300_gphi2e-1.h5',],
                     process = 'W+Z', parameters =['Gphi[TeV**-2]','GW[TeV**-2]'], 
                     SMNLimits=int(5e5), BSMNLimits=int(5e5))

td.Data = td.Data[:, :7]
td.CurateAngles([3, 5])

Data, ParVal, Labels, Weights = td.Data, td.ParVal, td.Labels, td.Weights
Data, ParVal, Labels, Weights = Data.float(), ParVal.float(), Labels.float(), Weights.float()

NSM = td.SMWeights.mean()*3000
NBSMList = [td.BSMWeightsList[i].mean()*3000 for i in range(len(td.BSMWeightsList))]

h = h5py.File(os.getcwd()+'/toydata/gphi_toydata_test_2e-1_in.h5', 'w')

h.create_dataset('Data', data=Data)
h.create_dataset('Weights', data=Weights)
h.create_dataset('Labels', data=Labels)
h.create_dataset('NSM', data = NSM)
h.create_dataset('NBSMList', data=NBSMList)

h.close()

Loading Data Files for Process: W+Z, with new physics Parameters: ['Gphi[TeV**-2]', 'GW[TeV**-2]']
Only 1D Implemented in Training !

Reading file .../madminer/madminer/examples/tutorial_particle_physics/toydata/ChP_pt300_gphi2e-1.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {0.2, 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_gphi2e-1.dat.gz
Charge = 1 --- Process = W+Z
#####

Reading file .../madminer/madminer/examples/tutorial_particle_physics/toydata/ChP_pt300_sm.h5
##### File Info:
SM = {0., 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_sm_1.dat.gz
Charge = 1 --- Process = W+Z
#####

Loaded SM Files:
['Gphi[TeV**-2]', 'GW[TeV**-2]']           #Data    XS[pb](avg.w)
---------------------------------------  -------  ---------------
tensor([[0., 0.]], dtype=tor

In [19]:
td = OurTrainingData([data_path+'/ChP_pt300_sm.h5'],
                     [data_path+'/ChP_pt300_gphi5e-1.h5',],
                     process = 'W+Z', parameters =['Gphi[TeV**-2]','GW[TeV**-2]'], 
                     SMNLimits=int(5e5), BSMNLimits=int(5e5))

td.Data = td.Data[:, :7]
td.CurateAngles([3, 5])

Data, ParVal, Labels, Weights = td.Data, td.ParVal, td.Labels, td.Weights
Data, ParVal, Labels, Weights = Data.float(), ParVal.float(), Labels.float(), Weights.float()

NSM = td.SMWeights.mean()*3000
NBSMList = [td.BSMWeightsList[i].mean()*3000 for i in range(len(td.BSMWeightsList))]

h = h5py.File(os.getcwd()+'/toydata/gphi_toydata_test_5e-1_in.h5', 'w')

h.create_dataset('Data', data=Data)
h.create_dataset('Weights', data=Weights)
h.create_dataset('Labels', data=Labels)
h.create_dataset('NSM', data = NSM)
h.create_dataset('NBSMList', data=NBSMList)

h.close()

Loading Data Files for Process: W+Z, with new physics Parameters: ['Gphi[TeV**-2]', 'GW[TeV**-2]']
Only 1D Implemented in Training !

Reading file .../madminer/madminer/examples/tutorial_particle_physics/toydata/ChP_pt300_gphi5e-1.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {0.5, 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_gphi5e-1.dat.gz
Charge = 1 --- Process = W+Z
#####

Reading file .../madminer/madminer/examples/tutorial_particle_physics/toydata/ChP_pt300_sm.h5
##### File Info:
SM = {0., 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_sm_1.dat.gz
Charge = 1 --- Process = W+Z
#####

Loaded SM Files:
['Gphi[TeV**-2]', 'GW[TeV**-2]']           #Data    XS[pb](avg.w)
---------------------------------------  -------  ---------------
tensor([[0., 0.]], dtype=tor

# Out Sample Test Data

In [32]:
td = OurTrainingData([data_path+'/ChP_pt300_sm_out.h5'],
                     [data_path+'/ChP_pt300_gphi6e-3.h5',],
                     process = 'W+Z', parameters =['Gphi[TeV**-2]','GW[TeV**-2]'], 
                     SMNLimits=int(3e6), BSMNLimits=int(3e6))

td.Data = td.Data[:, :7]
td.CurateAngles([3, 5])

Data, ParVal, Labels, Weights = td.Data, td.ParVal, td.Labels, td.Weights
Data, ParVal, Labels, Weights = Data.float(), ParVal.float(), Labels.float(), Weights.float()

NSM = td.SMWeights.mean()*3000
NBSMList = [td.BSMWeightsList[i].mean()*3000 for i in range(len(td.BSMWeightsList))]

h = h5py.File(os.getcwd()+'/toydata/gphi_toydata_test_6e-3_out.h5', 'w')

h.create_dataset('Data', data=Data)
h.create_dataset('Weights', data=Weights)
h.create_dataset('Labels', data=Labels)
h.create_dataset('NSM', data = NSM)
h.create_dataset('NBSMList', data=NBSMList)

h.close()

Loading Data Files for Process: W+Z, with new physics Parameters: ['Gphi[TeV**-2]', 'GW[TeV**-2]']
Only 1D Implemented in Training !

Reading file .../madminer/madminer/examples/tutorial_particle_physics/toydata/ChP_pt300_gphi6e-3.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {0.006, 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_gphi6e-3.dat.gz
Charge = 1 --- Process = W+Z
#####

Reading file .../madminer/madminer/examples/tutorial_particle_physics/toydata/ChP_pt300_sm_out.h5
##### File Info:
SM = {0., 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_sm_2.dat.gz
Charge = 1 --- Process = W+Z
#####

Loaded SM Files:
['Gphi[TeV**-2]', 'GW[TeV**-2]']           #Data    XS[pb](avg.w)
---------------------------------------  -------  ---------------
tensor([[0., 0.]], dty

In [33]:
td = OurTrainingData([data_path+'/ChP_pt300_sm_out.h5'],
                     [data_path+'/ChP_pt300_gphi5e-3.h5',],
                     process = 'W+Z', parameters =['Gphi[TeV**-2]','GW[TeV**-2]'], 
                     SMNLimits=int(3e6), BSMNLimits=int(3e6))

td.Data = td.Data[:, :7]
td.CurateAngles([3, 5])

Data, ParVal, Labels, Weights = td.Data, td.ParVal, td.Labels, td.Weights
Data, ParVal, Labels, Weights = Data.float(), ParVal.float(), Labels.float(), Weights.float()

NSM = td.SMWeights.mean()*3000
NBSMList = [td.BSMWeightsList[i].mean()*3000 for i in range(len(td.BSMWeightsList))]

h = h5py.File(os.getcwd()+'/toydata/gphi_toydata_test_5e-3_out.h5', 'w')

h.create_dataset('Data', data=Data)
h.create_dataset('Weights', data=Weights)
h.create_dataset('Labels', data=Labels)
h.create_dataset('NSM', data = NSM)
h.create_dataset('NBSMList', data=NBSMList)

h.close()

Loading Data Files for Process: W+Z, with new physics Parameters: ['Gphi[TeV**-2]', 'GW[TeV**-2]']
Only 1D Implemented in Training !

Reading file .../madminer/madminer/examples/tutorial_particle_physics/toydata/ChP_pt300_gphi5e-3.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {0.005, 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_gphi5e-3.dat.gz
Charge = 1 --- Process = W+Z
#####

Reading file .../madminer/madminer/examples/tutorial_particle_physics/toydata/ChP_pt300_sm_out.h5
##### File Info:
SM = {0., 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_sm_2.dat.gz
Charge = 1 --- Process = W+Z
#####

Loaded SM Files:
['Gphi[TeV**-2]', 'GW[TeV**-2]']           #Data    XS[pb](avg.w)
---------------------------------------  -------  ---------------
tensor([[0., 0.]], dty

In [34]:
td = OurTrainingData([data_path+'/ChP_pt300_sm_out.h5'],
                     [data_path+'/ChP_pt300_gphi4e-3.h5',],
                     process = 'W+Z', parameters =['Gphi[TeV**-2]','GW[TeV**-2]'], 
                     SMNLimits=int(3e6), BSMNLimits=int(3e6))

td.Data = td.Data[:, :7]
td.CurateAngles([3, 5])

Data, ParVal, Labels, Weights = td.Data, td.ParVal, td.Labels, td.Weights
Data, ParVal, Labels, Weights = Data.float(), ParVal.float(), Labels.float(), Weights.float()

NSM = td.SMWeights.mean()*3000
NBSMList = [td.BSMWeightsList[i].mean()*3000 for i in range(len(td.BSMWeightsList))]

h = h5py.File(os.getcwd()+'/toydata/gphi_toydata_test_4e-3_out.h5', 'w')

h.create_dataset('Data', data=Data)
h.create_dataset('Weights', data=Weights)
h.create_dataset('Labels', data=Labels)
h.create_dataset('NSM', data = NSM)
h.create_dataset('NBSMList', data=NBSMList)

h.close()

Loading Data Files for Process: W+Z, with new physics Parameters: ['Gphi[TeV**-2]', 'GW[TeV**-2]']
Only 1D Implemented in Training !

Reading file .../madminer/madminer/examples/tutorial_particle_physics/toydata/ChP_pt300_gphi4e-3.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {0.004, 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_gphi4e-3.dat.gz
Charge = 1 --- Process = W+Z
#####

Reading file .../madminer/madminer/examples/tutorial_particle_physics/toydata/ChP_pt300_sm_out.h5
##### File Info:
SM = {0., 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_sm_2.dat.gz
Charge = 1 --- Process = W+Z
#####

Loaded SM Files:
['Gphi[TeV**-2]', 'GW[TeV**-2]']           #Data    XS[pb](avg.w)
---------------------------------------  -------  ---------------
tensor([[0., 0.]], dty

In [25]:
td = OurTrainingData([data_path+'/ChP_pt300_sm_out.h5'],
                     [data_path+'/ChP_pt300_gphi35e-4.h5',],
                     process = 'W+Z', parameters =['Gphi[TeV**-2]','GW[TeV**-2]'], 
                     SMNLimits=int(5e5), BSMNLimits=int(5e5))

td.Data = td.Data[:, :7]
td.CurateAngles([3, 5])

Data, ParVal, Labels, Weights = td.Data, td.ParVal, td.Labels, td.Weights
Data, ParVal, Labels, Weights = Data.float(), ParVal.float(), Labels.float(), Weights.float()

NSM = td.SMWeights.mean()*3000
NBSMList = [td.BSMWeightsList[i].mean()*3000 for i in range(len(td.BSMWeightsList))]

h = h5py.File(os.getcwd()+'/toydata/gphi_toydata_test_35e-4_out.h5', 'w')

h.create_dataset('Data', data=Data)
h.create_dataset('Weights', data=Weights)
h.create_dataset('Labels', data=Labels)
h.create_dataset('NSM', data = NSM)
h.create_dataset('NBSMList', data=NBSMList)

h.close()

Loading Data Files for Process: W+Z, with new physics Parameters: ['Gphi[TeV**-2]', 'GW[TeV**-2]']
Only 1D Implemented in Training !

Reading file .../madminer/madminer/examples/tutorial_particle_physics/toydata/ChP_pt300_gphi35e-4.h5
##### File Info:
{Gphi[TeV**-2], GW[TeV**-2]} = {0.0035, 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_gphi35e-4.dat.gz
Charge = 1 --- Process = W+Z
#####

Reading file .../madminer/madminer/examples/tutorial_particle_physics/toydata/ChP_pt300_sm_out.h5
##### File Info:
SM = {0., 0.}[TeV**-2] data, Ideal Events. 
Event format: {{s, θ, θZ, ϕZ, θWrec, ϕWrec, PtZ}, weight}.
Converted from /data3/WZ_new_project/dat/Ideal_Events/ChP_pt300_sm_2.dat.gz
Charge = 1 --- Process = W+Z
#####

Loaded SM Files:
['Gphi[TeV**-2]', 'GW[TeV**-2]']           #Data    XS[pb](avg.w)
---------------------------------------  -------  ---------------
tensor([[0., 0.]], 